<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <AssemblyName>HaYTooL</AssemblyName>
    
    <!-- Yayıncı / Şirket / Telif bilgileri boş bırakıldı -->
    <Company></Company>
    <Product>HaYTooL</Product>
    <Copyright></Copyright>
    <Description></Description>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="app.ico" />
    <Resource Include="lol.png" />
    <Resource Include="valorant.png" />
  </ItemGroup>

</Project>
